import type { RootStackParamList } from '../navigation/AppNavigator';

export type DashboardFeature = {
  id: string;
  titleKey: string;
  subtitleKey: string;
  titleFallback: string;
  subtitleFallback: string;
  iconName: string;
  route: keyof RootStackParamList;
  color?: string;
  badgeCount?: number;
};

export const studentFeatures: DashboardFeature[] = [
  {
    id: 'attendance',
    titleKey: 'dashboard.myAttendance',
    subtitleKey: 'dashboard.myAttendanceSubtitle',
    titleFallback: 'My Attendance',
    subtitleFallback: 'Subject-wise percentage',
    iconName: 'analytics-outline',
    route: 'StudentAttendance',
    color: '#0EA5E9',
  },
  {
    id: 'apply-leave',
    titleKey: 'dashboard.applyLeave',
    subtitleKey: 'dashboard.applyLeaveSubtitle',
    titleFallback: 'Apply Leave',
    subtitleFallback: 'Request leave from teacher',
    iconName: 'calendar-outline',
    route: 'ApplyLeave',
    color: '#10B981',
  },
  {
    id: 'my-leaves',
    titleKey: 'dashboard.myLeaves',
    subtitleKey: 'dashboard.myLeavesSubtitle',
    titleFallback: 'My Leaves',
    subtitleFallback: 'Track leave requests',
    iconName: 'documents-outline',
    route: 'StudentLeaveList',
    color: '#22C55E',
  },
  {
    id: 'bonafide',
    titleKey: 'dashboard.bonafide',
    subtitleKey: 'dashboard.bonafideSubtitle',
    titleFallback: 'Bonafide Certificate',
    subtitleFallback: 'Request certificate',
    iconName: 'ribbon-outline',
    route: 'ApplyBonafide',
    color: '#8B5CF6',
  },
  {
    id: 'certificates',
    titleKey: 'dashboard.certificates',
    subtitleKey: 'dashboard.certificatesSubtitle',
    titleFallback: 'My Certificates',
    subtitleFallback: 'View approved certificates',
    iconName: 'medal-outline',
    route: 'StudentBonafideList',
    color: '#14B8A6',
  },
  {
    id: 'results',
    titleKey: 'dashboard.results',
    subtitleKey: 'dashboard.academicSubtitle',
    titleFallback: 'Results',
    subtitleFallback: 'Academic tools',
    iconName: 'bar-chart-outline',
    route: 'ViewResults',
    color: '#EF4444',
  },
  {
    id: 'assignments',
    titleKey: 'dashboard.assignments',
    subtitleKey: 'dashboard.assignmentsSubtitle',
    titleFallback: 'Assignments',
    subtitleFallback: 'Tasks and submissions',
    iconName: 'document-text-outline',
    route: 'StudentAssignments',
    color: '#F59E0B',
  },
  {
    id: 'resources',
    titleKey: 'dashboard.resources',
    subtitleKey: 'dashboard.resourcesSubtitle',
    titleFallback: 'Resources',
    subtitleFallback: 'Study materials from teachers',
    iconName: 'folder-open-outline',
    route: 'Resources',
    color: '#3B82F6',
  },
  {
    id: 'library',
    titleKey: 'dashboard.library',
    subtitleKey: 'dashboard.librarySubtitle',
    titleFallback: 'E-Library',
    subtitleFallback: 'Books, PDFs and notes',
    iconName: 'library-outline',
    route: 'ELibrary',
    color: '#6366F1',
  },
  {
    id: 'gallery',
    titleKey: 'dashboard.gallery',
    subtitleKey: 'dashboard.gallerySubtitle',
    titleFallback: 'Event Gallery',
    subtitleFallback: 'View and share events',
    iconName: 'images-outline',
    route: 'EventGallery',
    color: '#EC4899',
  },
  {
    id: 'groups',
    titleKey: 'dashboard.groups',
    subtitleKey: 'dashboard.groupsSubtitle',
    titleFallback: 'Groups',
    subtitleFallback: 'Class groups and messages',
    iconName: 'people-outline',
    route: 'StudentGroups',
    color: '#06B6D4',
  },
];

export const teacherFeatures: DashboardFeature[] = [
  {
    id: 'take-attendance',
    titleKey: 'dashboard.takeAttendance',
    subtitleKey: 'dashboard.takeAttendanceSubtitle',
    titleFallback: 'Take Attendance',
    subtitleFallback: 'Mark live face attendance',
    iconName: 'scan-outline',
    route: 'TeacherAttendanceSetup',
    color: '#2563EB',
  },
  {
    id: 'requests-hub',
    titleKey: 'dashboard.requestsHub',
    subtitleKey: 'dashboard.requestsHubSubtitle',
    titleFallback: 'Requests Hub',
    subtitleFallback: 'Leave and bonafide requests',
    iconName: 'file-tray-full-outline',
    route: 'TeacherRequests',
    color: '#8B5CF6',
  },
  {
    id: 'teacher-assignments',
    titleKey: 'dashboard.teacherAssignments',
    subtitleKey: 'dashboard.teacherAssignmentsSubtitle',
    titleFallback: 'Assignments',
    subtitleFallback: 'Create and review assignments',
    iconName: 'document-text-outline',
    route: 'TeacherAssignments',
    color: '#F59E0B',
  },
  {
    id: 'teacher-resources',
    titleKey: 'dashboard.teacherResources',
    subtitleKey: 'dashboard.teacherResourcesSubtitle',
    titleFallback: 'Resources',
    subtitleFallback: 'Upload study materials',
    iconName: 'folder-open-outline',
    route: 'TeacherELibrary',
    color: '#0EA5E9',
  },
  {
    id: 'upload-results',
    titleKey: 'dashboard.uploadResults',
    subtitleKey: 'dashboard.uploadResultsSubtitle',
    titleFallback: 'Upload Results',
    subtitleFallback: 'Publish student marks',
    iconName: 'bar-chart-outline',
    route: 'UploadResult',
    color: '#EF4444',
  },
  {
    id: 'class-groups',
    titleKey: 'dashboard.groups',
    subtitleKey: 'dashboard.groupsSubtitle',
    titleFallback: 'Class Groups',
    subtitleFallback: 'Class groups and messages',
    iconName: 'people-outline',
    route: 'TeacherGroups',
    color: '#06B6D4',
  },
  {
    id: 'event-gallery',
    titleKey: 'dashboard.gallery',
    subtitleKey: 'dashboard.gallerySubtitle',
    titleFallback: 'Event Gallery',
    subtitleFallback: 'View and share events',
    iconName: 'images-outline',
    route: 'EventGallery',
    color: '#EC4899',
  },
  {
    id: 'signature',
    titleKey: 'dashboard.signature',
    subtitleKey: 'dashboard.signatureSubtitle',
    titleFallback: 'My Signature',
    subtitleFallback: 'Manage approval signature',
    iconName: 'create-outline',
    route: 'TeacherSignature',
    color: '#14B8A6',
  },
  {
    id: 'reports',
    titleKey: 'dashboard.reports',
    subtitleKey: 'dashboard.reportsSubtitle',
    titleFallback: 'Attendance Reports',
    subtitleFallback: 'View and export reports',
    iconName: 'stats-chart-outline',
    route: 'TeacherLeaveRequests',
    color: '#A855F7',
  },
];
